import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "npm/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="my-2">
          <h1>Medic AI</h1>
        </div>
        <div className="my-2">
          <h2>User Query goes here</h2>
        </div>
        <div className="my-2 rounded-md border border-r-black">
          <input />
        </div>
      </main>
    </>
  );
};

export default Home;
